export enum MessageType {
  HELLO = 0,
  WELCOME = 1,
  SPAWN = 2,
  DESPAWN = 3,
  MOVE = 4,
  LOOTMOVE = 5,
  AGGRO = 6,
  ATTACK = 7,
  HIT = 8,
  HURT = 9,
  HEALTH = 10,
  CHAT = 11,
  LOOT = 12,
  EQUIP = 13,
  DROP = 14,
  TELEPORT = 15,
  DAMAGE = 16,
  POPULATION = 17,
  KILL = 18,
  LIST = 19,
  WHO = 20,
  ZONE = 21,
  DESTROY = 22,
  HP = 23,
  BLINK = 24,
  OPEN = 25,
  CHECK = 26,
}

export enum EntityKind {
  WARRIOR = 1,

  // Mobs
  RAT = 2,
  SKELETON = 3,
  GOBLIN = 4,
  OGRE = 5,
  SPECTRE = 6,
  CRAB = 7,
  BAT = 8,
  WIZARD = 9,
  EYE = 10,
  SNAKE = 11,
  SKELETON2 = 12,
  BOSS = 13,
  DEATHKNIGHT = 14,

  // Armors
  FIREFOX = 20,
  CLOTHARMOR = 21,
  LEATHERARMOR = 22,
  MAILARMOR = 23,
  PLATEARMOR = 24,
  REDARMOR = 25,
  GOLDENARMOR = 26,

  // Objects
  FLASK = 35,
  BURGER = 36,
  CHEST = 37,
  FIREPOTION = 38,
  CAKE = 39,

  // NPCs
  GUARD = 40,
  KING = 41,
  OCTOCAT = 42,
  VILLAGEGIRL = 43,
  VILLAGER = 44,
  PRIEST = 45,
  SCIENTIST = 46,
  AGENT = 47,
  RICK = 48,
  NYAN = 49,
  SORCERER = 50,
  BEACHNPC = 51,
  FORESTNPC = 52,
  DESERTNPC = 53,
  LAVANPC = 54,
  CODER = 55,

  // Weapons
  SWORD1 = 60,
  SWORD2 = 61,
  REDSWORD = 62,
  GOLDENSWORD = 63,
  MORNINGSTAR = 64,
  AXE = 65,
  BLUESWORD = 66,
}

export enum Orientation {
  UP = 1,
  DOWN = 2,
  LEFT = 3,
  RIGHT = 4,
}

export type EntityType = 'player' | 'mob' | 'weapon' | 'armor' | 'object' | 'npc';

export type EntityId = number | string;
export type SpriteId = string;

export const EntityKindMap = {
  [EntityKind.WARRIOR]: ['warrior', 'player'],
  [EntityKind.RAT]: ['rat', 'mob'],
  [EntityKind.SKELETON]: ['skeleton', 'mob'],
  [EntityKind.GOBLIN]: ['goblin', 'mob'],
  [EntityKind.OGRE]: ['ogre', 'mob'],
  [EntityKind.SPECTRE]: ['spectre', 'mob'],
  [EntityKind.CRAB]: ['crab', 'mob'],
  [EntityKind.BAT]: ['bat', 'mob'],
  [EntityKind.WIZARD]: ['wizard', 'mob'],
  [EntityKind.EYE]: ['eye', 'mob'],
  [EntityKind.SNAKE]: ['snake', 'mob'],
  [EntityKind.SKELETON2]: ['skeleton2', 'mob'],
  [EntityKind.BOSS]: ['boss', 'mob'],
  [EntityKind.DEATHKNIGHT]: ['deathknight', 'mob'],
  [EntityKind.FIREFOX]: ['firefox', 'armor'],
  [EntityKind.CLOTHARMOR]: ['clotharmor', 'armor'],
  [EntityKind.LEATHERARMOR]: ['leatherarmor', 'armor'],
  [EntityKind.MAILARMOR]: ['mailarmor', 'armor'],
  [EntityKind.PLATEARMOR]: ['platearmor', 'armor'],
  [EntityKind.REDARMOR]: ['redarmor', 'armor'],
  [EntityKind.GOLDENARMOR]: ['goldenarmor', 'armor'],
  [EntityKind.FLASK]: ['flask', 'object'],
  [EntityKind.BURGER]: ['burger', 'object'],
  [EntityKind.CHEST]: ['chest', 'object'],
  [EntityKind.FIREPOTION]: ['firepotion', 'object'],
  [EntityKind.CAKE]: ['cake', 'object'],
  [EntityKind.GUARD]: ['guard', 'npc'],
  [EntityKind.KING]: ['king', 'npc'],
  [EntityKind.OCTOCAT]: ['octocat', 'npc'],
  [EntityKind.VILLAGEGIRL]: ['villagegirl', 'npc'],
  [EntityKind.VILLAGER]: ['villager', 'npc'],
  [EntityKind.PRIEST]: ['priest', 'npc'],
  [EntityKind.SCIENTIST]: ['scientist', 'npc'],
  [EntityKind.AGENT]: ['agent', 'npc'],
  [EntityKind.RICK]: ['rick', 'npc'],
  [EntityKind.NYAN]: ['nyan', 'npc'],
  [EntityKind.SORCERER]: ['sorcerer', 'npc'],
  [EntityKind.BEACHNPC]: ['beachnpc', 'npc'],
  [EntityKind.FORESTNPC]: ['forestnpc', 'npc'],
  [EntityKind.DESERTNPC]: ['desertnpc', 'npc'],
  [EntityKind.LAVANPC]: ['lavanpc', 'npc'],
  [EntityKind.CODER]: ['coder', 'npc'],
  [EntityKind.SWORD1]: ['sword1', 'weapon'],
  [EntityKind.SWORD2]: ['sword2', 'weapon'],
  [EntityKind.REDSWORD]: ['redsword', 'weapon'],
  [EntityKind.GOLDENSWORD]: ['goldensword', 'weapon'],
  [EntityKind.MORNINGSTAR]: ['morningstar', 'weapon'],
  [EntityKind.AXE]: ['axe', 'weapon'],
  [EntityKind.BLUESWORD]: ['bluesword', 'weapon'],
} satisfies Record<EntityKind, [string, EntityType]>;

export const RankedWeapons = [
  EntityKind.SWORD1,
  EntityKind.SWORD2,
  EntityKind.AXE,
  EntityKind.MORNINGSTAR,
  EntityKind.BLUESWORD,
  EntityKind.REDSWORD,
  EntityKind.GOLDENSWORD,
];

export const RankedArmors = [
  EntityKind.CLOTHARMOR,
  EntityKind.LEATHERARMOR,
  EntityKind.MAILARMOR,
  EntityKind.PLATEARMOR,
  EntityKind.REDARMOR,
  EntityKind.GOLDENARMOR,
];
